Add "isLocked" and "isVisible" utility functions #68
yuanqing/create-figma-plugin pull request #75
Opened 2021-11-30 09:40 UTC by saeedalipoor

2021-11-30 11:39 UTC, yuanqing requested changes
Thanks for this!

Prefer if the API is specific to `SceneNode` rather than `BaseNode`, to be consistent with all the other utility functions. In particular, locked/unlocked and visibility only really applies to `SceneNode`?

For example:

```ts
export function isLocked(node: SceneNode): boolean {
  if (node.locked === false) {
    return false
  }
  if (node.parent === null || node.parent.type === 'PAGE') {
    return true
  }
  return isLocked(node.parent as SceneNode)
}
```

2021-11-30 13:39 UTC, yuanqing commented on packages/utilities/src/node/is-locked.ts
> +  }
I think this should be:

```
  if (node.locked === false) {
    return false
  }
  if (node.parent === null || node.parent.type === 'PAGE') {
    return true
  }
```

2021-11-30 13:43 UTC, saeedalipoor commented on packages/utilities/src/node/is-locked.ts
> +  }
As the function name is `isLocked` so the return value should be true when the `node.locked` is true, right?

2021-11-30 13:48 UTC, yuanqing commented on packages/utilities/src/node/is-locked.ts
> +  }
Ahh, you’re right. As long as `locked`== `true`, we know that the layer is `locked`. Otherwise we need to traverse up the tree to check if any parent node has `locked` == `true`. Got it.

2021-11-30 13:49 UTC, merged

2021-11-30 13:50 UTC, saeedalipoor commented on packages/utilities/src/node/is-locked.ts
> +  }
Yup, that's it 🤘

2021-12-06 10:38 UTC, yuanqing commented
Shipped in `1.8.0`